spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/microservices
    username: root
    password: VK@225
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: bgic txqx qhwv foxc
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: manideep.pagadala@gmail.com
  main:
    banner-mode: off
  application:
    name: CO-API
  boot:
    admin:
      client:
        url: http://localhost:9090/
management:
  endpoints:
    web:
      exposure:
        include: '*'
