spring:
  application:
    name: SSN-SERVICE-PROVIDER
  boot:
    admin:
      client:
        url:
          - http://localhost:9090/

management:
  endpoints:
    web:
      exposure:
        include: '*'
